DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
            user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_name VARCHAR(40) NOT NULL,
            email VARCHAR(40) NOT NULL UNIQUE
          );

CREATE TABLE IF NOT EXISTS requests (
            request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            description VARCHAR(200) NOT NULL,
            requestor_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
            created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
           );

CREATE TABLE IF NOT EXISTS items (
            item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_name VARCHAR(40) NOT NULL,
            description VARCHAR(200) NOT NULL,
            is_available BOOLEAN NOT NULL,
            owner_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
            request_id BIGINT REFERENCES requests(request_id) ON DELETE CASCADE
           );

CREATE TABLE IF NOT EXISTS bookings (
            booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE,
            booker_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
            status VARCHAR(15) DEFAULT 'WAITING' NOT NULL,
            CONSTRAINT chk_booking_status CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED')),
            CONSTRAINT chk_booking_dates CHECK (end_date > start_date)
           );

CREATE TABLE IF NOT EXISTS comments (
            comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            text VARCHAR(200) NOT NULL,
            item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE,
            author_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
            created TIMESTAMP WITHOUT TIME ZONE NOT NULL
           );